insert into public.warilo_products (
  id,
  seller_id,
  title,
  description,
  category,
  product_type,
  brand,
  purchase_note,
  condition_label,
  authenticity_note,
  estimated_market_price_fcfa,
  price_fcfa,
  images,
  stock,
  status
) values (
  '22222222-0011-4222-8222-222222222222',
  '11111111-1111-4111-8111-111111111111',
  'Baylis & Harding Goodness Oud, Cedar & Amber',
  'Gel lavant naturel 1 litre Baylis & Harding Goodness, parfum Oud, Cèdre et Ambre, avec une signature chaude, boisée et élégante.',
  'Beauté',
  'other',
  'Baylis & Harding',
  'Un grand format pratique pour la maison, idéal pour une routine douche parfumée. Notes de tête orange, citron et bergamote, cœur jasmin et basilic, fond oud, cèdre, ambre et bois de santal.',
  'Neuf, flacon pompe 1 litre',
  'Produit vendu par l''équipe Yapalaan. 98% d''origine naturelle selon l''étiquette du produit.',
  15000,
  10000,
  '["/assets/yapalaan-product-oud-cedar-amber-body-wash.png"]'::jsonb,
  5,
  'active'
) on conflict (id) do update set
  title = excluded.title,
  description = excluded.description,
  category = excluded.category,
  product_type = excluded.product_type,
  brand = excluded.brand,
  purchase_note = excluded.purchase_note,
  condition_label = excluded.condition_label,
  authenticity_note = excluded.authenticity_note,
  estimated_market_price_fcfa = excluded.estimated_market_price_fcfa,
  price_fcfa = excluded.price_fcfa,
  images = excluded.images,
  stock = excluded.stock,
  status = excluded.status;
