import type { WariloDemoData } from "./warilo";

export const yapalaanDemoData: WariloDemoData = {
  mode: "local-demo",
  categories: ["Montres", "Sport"],
  seller: {
    id: "seller_yapalaan_officiel",
    storeName: "Yapalaan",
    slug: "yapalaan-officiel",
    commune: "Cocody",
    phone: "+225 05 00 00 00 00",
    whatsapp: "+225 07 00 00 00 00",
    email: "contact@yapalaan.ci",
    locationLabel: "Cocody Riviera, Abidjan",
    latitude: 5.3599,
    longitude: -4.0083,
    verificationStatus: "verified",
    trustLevel: "Boutique officielle - Produit vérifié",
    rating: 4.9,
    reviewCount: 48,
  },
  products: [
    {
      id: "product_adidas_gazelle_lux_blue",
      name: "Adidas Gazelle Lux Spikeless Golf Shoes",
      short: "Adidas Gazelle Lux",
      category: "Sport",
      productType: "shoes",
      brand: "Adidas",
      description: "Chaussures Adidas Gazelle Lux bleu marine, taille unique 42, style polyvalent et semelle confortable.",
      purchaseNote: "Taille unique 42. Idéal pour une tenue sport chic, le quotidien ou les sorties décontractées.",
      condition: "Neuf",
      authenticityNote: "Produit contrôlé par l'équipe Yapalaan avant livraison.",
      estimatedMarketPriceFcfa: 120000,
      priceFcfa: 90000,
      imageUrl: "/assets/yapalaan-product-blue-adidas.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_beverly_hills_polo_blue_watch",
      name: "Beverly Hills Polo Club montre homme bleue",
      short: "Beverly Hills bleue",
      category: "Montres",
      productType: "watch",
      brand: "Beverly Hills Polo Club",
      description: "Montre homme Beverly Hills Polo Club au cadran bleu, bracelet acier et style sport élégant.",
      purchaseNote: "Convient au quotidien comme aux occasions habillées. Bracelet ajustable selon le poignet.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 125000,
      priceFcfa: 100000,
      imageUrl: "/assets/yapalaan-product-beverly-hills-blue.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_guess_bicolor_watch",
      name: "Guess montre homme bicolore",
      short: "Guess bicolore",
      category: "Montres",
      productType: "watch",
      brand: "Guess",
      description: "Montre homme Guess bicolore argent et or, cadran brillant et finition premium.",
      purchaseNote: "Pièce voyante pour une tenue élégante, les sorties ou les événements spéciaux.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 145000,
      priceFcfa: 110000,
      imageUrl: "/assets/yapalaan-product-guess-watch.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_ingersoll_automatic_silver_watch",
      name: "Ingersoll montre automatique argent",
      short: "Ingersoll automatique",
      category: "Montres",
      productType: "watch",
      brand: "Ingersoll",
      description: "Montre automatique Ingersoll argent, cadran noir et mouvement mécanique apparent.",
      purchaseNote: "Choix recommandé pour les amateurs de montres automatiques et de finitions classiques.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 195000,
      priceFcfa: 150000,
      imageUrl: "/assets/yapalaan-product-ingersoll-automatic-1.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_ingersoll_automatic_black_watch",
      name: "Ingersoll montre automatique noire",
      short: "Ingersoll prestige",
      category: "Montres",
      productType: "watch",
      brand: "Ingersoll",
      description: "Montre automatique Ingersoll noire, finition acier, cadran sophistiqué et présentation premium.",
      purchaseNote: "Modèle premium à offrir ou à porter pour un style habillé et durable.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 260000,
      priceFcfa: 200000,
      imageUrl: "/assets/yapalaan-product-ingersoll.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_perry_ellis_solar_blue_watch",
      name: "Perry Ellis montre solaire bleue",
      short: "Perry Ellis solaire",
      category: "Montres",
      productType: "watch",
      brand: "Perry Ellis",
      description: "Montre solaire Perry Ellis au cadran bleu, bracelet maille milanaise et design épuré.",
      purchaseNote: "Se recharge à la lumière. Bon choix pour éviter le changement fréquent de pile.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 145000,
      priceFcfa: 110000,
      imageUrl: "/assets/yapalaan-product-perry-ellis.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_beverly_hills_polo_women_gold_silver_watch",
      name: "Beverly Hills Polo Club montre femme or et argent",
      short: "Beverly Hills femme",
      category: "Montres",
      productType: "watch",
      brand: "Beverly Hills Polo Club",
      description: "Montre femme Beverly Hills Polo Club or et argent, détails cristal et finition raffinée.",
      purchaseNote: "Modèle féminin élégant, adapté au quotidien, aux cérémonies et aux cadeaux.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 95000,
      priceFcfa: 70000,
      imageUrl: "/assets/yapalaan-product-polo-club-2-watch.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_us_polo_assn_classic_watch",
      name: "U.S. Polo Assn montre classique",
      short: "U.S. Polo classique",
      category: "Montres",
      productType: "watch",
      brand: "U.S. Polo Assn.",
      description: "Montre U.S. Polo Assn classique avec bracelet cuir noir et cadran blanc épuré.",
      purchaseNote: "Style intemporel, facile à porter au travail, au quotidien ou pour offrir.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 85000,
      priceFcfa: 60000,
      imageUrl: "/assets/yapalaan-product-polo1.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_thomas_templer_limited_watch",
      name: "Thomas Templer montre homme Limited Edition",
      short: "Thomas Templer",
      category: "Montres",
      productType: "watch",
      brand: "Thomas Templer",
      description: "Montre homme Thomas Templer Limited Edition, cadran violet et mouvement automatique apparent.",
      purchaseNote: "Pièce distinctive pour acheteur recherchant un style plus affirmé et collectionnable.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 275000,
      priceFcfa: 200000,
      imageUrl: "/assets/yapalaan-product-thomas-templer.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
    {
      id: "product_us_polo_assn_blue_leather_watch",
      name: "U.S. Polo Assn montre homme cuir bleu",
      short: "U.S. Polo cuir bleu",
      category: "Montres",
      productType: "watch",
      brand: "U.S. Polo Assn.",
      description: "Montre homme U.S. Polo Assn avec bracelet cuir et cadran bleu profond.",
      purchaseNote: "Design sobre et habillé, adapté aux tenues professionnelles ou aux sorties.",
      condition: "Neuf, emballage disponible",
      authenticityNote: "Contrôle Yapalaan avant remise au livreur.",
      estimatedMarketPriceFcfa: 85000,
      priceFcfa: 60000,
      imageUrl: "/assets/yapalaan-product-us-polo.png",
      tag: "Yapalaan",
      sellerId: "seller_yapalaan_officiel",
      stock: 1,
      availability: "available",
    },
  ],
  couriers: [
    {
      id: "courier_montal_coursier",
      fullName: "MONTAL COURSIER",
      phone: "+225 05 04 95 81 53",
      commune: "Treichville",
      zone: "Livraison express, coursier urbain, colis et services logistiques.",
      vehicleType: "moto",
      eta: "Aujourd'hui - 2 h",
      deliveryFeeFcfa: 1500,
      averageRating: 4.8,
      ratingsCount: 12,
      locationLabel: "Treichville Avenue 3, Rue 17, Abidjan",
      latitude: 5.299,
      longitude: -4.006,
    },
    {
      id: "courier_colis_express_abidjan",
      fullName: "Colis Express Abidjan",
      phone: "+225 07 47 47 43 34",
      commune: "Abidjan",
      zone: "Livraison de colis, expédition locale et transport rapide.",
      vehicleType: "moto",
      eta: "Aujourd'hui - 3 h",
      deliveryFeeFcfa: 1700,
      averageRating: 4.7,
      ratingsCount: 10,
      locationLabel: "Cité Bureau Promogim, Feh Kessé, Abidjan",
      latitude: 5.36,
      longitude: -4.008,
    },
    {
      id: "courier_royal_courrier",
      fullName: "Royal Courrier",
      phone: "Non affiché publiquement",
      commune: "Abidjan",
      zone: "Courrier express, documents et colis pour particuliers et entreprises.",
      vehicleType: "van",
      eta: "Demain matin",
      deliveryFeeFcfa: 2200,
      averageRating: 4.5,
      ratingsCount: 6,
      locationLabel: "21 BP 1627 Abidjan 21, Abidjan",
      latitude: 5.348,
      longitude: -4.024,
    },
    {
      id: "courier_cargo_colis_express",
      fullName: "CARGO COLIS EXPRESS",
      phone: "+225 01 42 87 17 22",
      commune: "Abidjan",
      zone: "Livraison B2B, transport de marchandises et colis professionnels.",
      vehicleType: "van",
      eta: "Aujourd'hui - 4 h",
      deliveryFeeFcfa: 2500,
      averageRating: 4.6,
      ratingsCount: 8,
      locationLabel: "Abidjan",
      latitude: 5.345,
      longitude: -4.024,
    },
    {
      id: "courier_cap_logistics",
      fullName: "CAP LOGISTICS sa",
      phone: "+225 27 21 24 65 00",
      commune: "Abidjan",
      zone: "Logistique, transport routier, fret et livraison d'entreprise.",
      vehicleType: "van",
      eta: "Demain matin",
      deliveryFeeFcfa: 3000,
      averageRating: 4.6,
      ratingsCount: 9,
      locationLabel: "BP 120 Post'Entreprise Cedex 01, Abidjan",
      latitude: 5.336,
      longitude: -4.027,
    },
    {
      id: "courier_lit_logistique_ivoire_transport",
      fullName: "(LIT) LOGISTIQUE IVOIRE TRANSPORT",
      phone: "+225 05 44 18 61 64",
      commune: "Cocody",
      zone: "Livraison, logistique urbaine, transport de colis et marchandises.",
      vehicleType: "moto",
      eta: "Aujourd'hui - 3 h",
      deliveryFeeFcfa: 1600,
      averageRating: 4.7,
      ratingsCount: 11,
      locationLabel: "Cocody Angré, zone Petro-Ivoire, Abidjan",
      latitude: 5.399,
      longitude: -3.967,
    },
    {
      id: "courier_kems_business",
      fullName: "KEM'S BUSINESS by GIE COLIS EXPRESS",
      phone: "+225 05 65 70 06 03",
      commune: "Angré",
      zone: "Expédition de colis, courrier et livraison locale.",
      vehicleType: "moto",
      eta: "Aujourd'hui - 3 h",
      deliveryFeeFcfa: 1600,
      averageRating: 4.7,
      ratingsCount: 7,
      locationLabel: "Angré, Abidjan",
      latitude: 5.392,
      longitude: -3.965,
    },
    {
      id: "courier_weni",
      fullName: "Weni",
      phone: "+225 07 89 64 39 48",
      commune: "Abidjan",
      zone: "Livraison de colis, messagerie et expédition.",
      vehicleType: "moto",
      eta: "Aujourd'hui - 2 h",
      deliveryFeeFcfa: 1400,
      averageRating: 4.8,
      ratingsCount: 13,
      locationLabel: "S.I.T.I.N Commissionnaire, Avenue 21, Abidjan",
      latitude: 5.313,
      longitude: -4.005,
    },
    {
      id: "courier_intercargo_ci",
      fullName: "Intercargo - Côte d'Ivoire",
      phone: "+225 07 02 60 34 85",
      commune: "Abidjan",
      zone: "Fret, import-export, logistique et expédition nationale/internationale.",
      vehicleType: "van",
      eta: "Demain matin",
      deliveryFeeFcfa: 3200,
      averageRating: 4.5,
      ratingsCount: 8,
      locationLabel: "427 Rue Nassalatou Diaby, Abidjan",
      latitude: 5.347,
      longitude: -4.011,
    },
    {
      id: "courier_viite",
      fullName: "Viite - Société de livraison",
      phone: "+225 07 67 63 20 78",
      commune: "Riviera",
      zone: "Livraison rapide et transport local de colis.",
      vehicleType: "moto",
      eta: "Aujourd'hui - 2 h",
      deliveryFeeFcfa: 1300,
      averageRating: 4.8,
      ratingsCount: 14,
      locationLabel: "Riviera, Abidjan",
      latitude: 5.37,
      longitude: -3.974,
    },
    {
      id: "courier_bl_express",
      fullName: "BL Express",
      phone: "+225 07 04 31 66 05",
      commune: "Abidjan",
      zone: "Livraison express et services de transport de colis.",
      vehicleType: "moto",
      eta: "Aujourd'hui - 3 h",
      deliveryFeeFcfa: 1500,
      averageRating: 4.6,
      ratingsCount: 9,
      locationLabel: "Abidjan",
      latitude: 5.348,
      longitude: -4.024,
    },
    {
      id: "courier_dhl_atlantis_voyages",
      fullName: "DHL Service Point (ATLANTIS VOYAGES)",
      phone: "+225 27 21 21 99 98",
      commune: "Abidjan",
      zone: "Livraison express internationale, courrier et expédition de colis.",
      vehicleType: "van",
      eta: "Demain matin",
      deliveryFeeFcfa: 4500,
      averageRating: 4.9,
      ratingsCount: 20,
      locationLabel: "Carrefour Hôtel Coquette, Abidjan",
      latitude: 5.35,
      longitude: -4.02,
    },
  ],
  buyerDeliveryContact: {
    phone: "+225 07 12 34 56 78",
    whatsapp: "+225 07 12 34 56 78",
    email: "acheteur@email.com",
    locationLabel: "5.3599, -4.0083 - Cocody Riviera",
    latitude: 5.3599,
    longitude: -4.0083,
    deliveryInstructions: "Derrière la pharmacie Ivoire, immeuble jaune, 2e étage à gauche",
  },
};
